# Use the official Python image as the base image
FROM python:3.8-slim

# create a working directory
WORKDIR /app

# Copy the Python script and any other necessary files to the working directory
COPY consumer.py /app/consumer.py

# Install the necessary dependencies
RUN pip install pika

# Run the Python script when the container starts
CMD ["python3", "consumer.py"]