version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbit-server
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672" # RabbitMQ management console port
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - rabbitmq
      - consumer
    restart: on-failure

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
    

volumes:
  rabbitmq_data:
